destination: animations.js
template: template.js
placeholder: "@@ANIMATIONS@@"
line_template: "{prefix}JSVEE.animations['{name}'] = {data};\n"

default_test: "*.animation.json"

packages_dir: /opt/jsvee/

copy:
  - source: /opt/jsvee/
    files:
      - engine.js
      - offline.js
      - messages_fi.json
      - pics/
      - jsvee.css
